import Link from "next/link";
function Nav() {
  return (<nav className="border-b border-white/8 px-6 py-4 flex items-center justify-between sticky top-0 bg-zinc-950/90 backdrop-blur-xl z-50"><Link href="/" className="flex items-center gap-2.5"><div className="w-7 h-7 rounded-md bg-indigo-600 flex items-center justify-center"><span className="font-black text-white text-xs">UTH</span></div><span className="font-black tracking-tighter text-lg"><span className="text-indigo-400">U</span><span className="text-indigo-300">T</span><span className="text-indigo-200">H</span></span></Link><div className="flex gap-4 text-sm text-zinc-400"><Link href="/privacy" className="hover:text-white">Privacy</Link><Link href="/terms" className="hover:text-white">Terms</Link><Link href="/gdpr" className="hover:text-white">GDPR</Link></div></nav>);
}
const COOKIE_TYPES = [
  { name: "Strictly Necessary", required: true, examples: "Session token (access_token), refresh_token, CSRF token", purpose: "Required for authentication and platform security. Cannot be disabled." },
  { name: "Functional", required: false, examples: "Language preference, theme preference", purpose: "Remember your settings to improve your experience." },
  { name: "Analytics", required: false, examples: "Page view counts, feature usage metrics (anonymised)", purpose: "Help us understand how users interact with UTH so we can improve the product." },
  { name: "Marketing", required: false, examples: "Campaign attribution, referral source", purpose: "Used to measure the effectiveness of our marketing campaigns." },
];
export default function CookiesPage() {
  return (<div className="min-h-screen bg-zinc-950 text-white"><Nav /><div className="max-w-3xl mx-auto px-6 py-16">
    <div className="mb-12"><div className="text-xs text-zinc-500 uppercase tracking-widest mb-2">Legal · UTH</div><h1 className="text-4xl font-black text-white mb-3">Cookie Policy</h1><p className="text-zinc-500 text-sm">Last updated: 01 April 2025</p></div>
    <p className="text-zinc-400 leading-relaxed mb-10">This Cookie Policy explains how the UTH platform uses cookies and similar tracking technologies. By using the UTH platform, you consent to our use of cookies as described in this policy.</p>
    <section className="mb-10"><h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-zinc-800">What are cookies?</h2><p className="text-zinc-400 text-sm leading-relaxed">Cookies are small text files placed on your device when you visit a website. They are widely used to make websites work, improve efficiency, and provide analytical information to site owners. The UTH platform uses cookies primarily to maintain your authenticated session securely.</p></section>
    <section className="mb-10"><h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-zinc-800">Types of cookies we use</h2>
      <div className="space-y-4">
        {COOKIE_TYPES.map(c => (<div key={c.name} className="rounded-xl border border-zinc-800 bg-zinc-900 p-5"><div className="flex items-start justify-between mb-2"><h3 className="font-semibold text-white">{c.name}</h3>{c.required ? <span className="text-xs bg-indigo-600 text-white px-2 py-0.5 rounded">Required</span> : <span className="text-xs border border-zinc-700 text-zinc-400 px-2 py-0.5 rounded">Optional</span>}</div><p className="text-zinc-400 text-sm mb-2">{c.purpose}</p><p className="text-zinc-500 text-xs"><span className="text-zinc-400">Examples: </span>{c.examples}</p></div>))}
      </div>
    </section>
    <section className="mb-10"><h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-zinc-800">UTH platform cookies</h2><p className="text-zinc-400 text-sm leading-relaxed mb-3">The UTH platform sets the following cookies for authenticated users:</p>
      <div className="overflow-auto rounded-xl border border-zinc-800"><table className="w-full text-sm"><thead><tr className="bg-zinc-900 border-b border-zinc-800"><th className="text-left px-4 py-3 text-zinc-400 font-medium">Cookie</th><th className="text-left px-4 py-3 text-zinc-400 font-medium">Purpose</th><th className="text-left px-4 py-3 text-zinc-400 font-medium">Expiry</th></tr></thead><tbody>
        {[["access_token","JWT access token — authenticates API requests","15 minutes"],["refresh_token","Refresh token — obtains new access tokens","30 days"],["sca_token","Temporary token during SCA challenge flow","10 minutes"]].map(([name,purpose,expiry]) => (<tr key={name} className="border-t border-zinc-800/50"><td className="px-4 py-3 font-mono text-indigo-300 text-xs">{name}</td><td className="px-4 py-3 text-zinc-400">{purpose}</td><td className="px-4 py-3 text-zinc-500">{expiry}</td></tr>))}
      </tbody></table></div>
    </section>
    <section className="mb-10"><h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-zinc-800">Managing cookies</h2><p className="text-zinc-400 text-sm leading-relaxed">You can control and/or delete cookies at any time. You may set your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you disable strictly necessary cookies, you will not be able to log in to the UTH platform. For analytics and marketing cookies, you may opt out at any time via our cookie preference centre.</p></section>
    <section className="mb-10"><h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-zinc-800">Changes to this policy</h2><p className="text-zinc-400 text-sm leading-relaxed">We reserve the right to modify this Cookie Policy at any time. Updates will be published on our platform. Continued use constitutes acceptance of any changes.</p></section>
  </div><footer className="border-t border-white/8 px-6 py-6 text-center text-zinc-700 text-xs"><Link href="/" className="hover:text-zinc-400">← Back to UTH</Link></footer></div>);
}
