import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json(SPEC, {
    headers: { "Access-Control-Allow-Origin": "*" }
  });
}

const SPEC = {
  openapi:"3.0.3",
  info:{ title:"UTH Authentication Platform API", version:"1.0.0", description:"Production-grade authentication API by Empatix. JWT sessions, WebAuthn, Risk Engine, Device Attestation, SCA/PSD2 — as a single service.", contact:{ name:"Empatixtech", email:"sales@empatixtech.com" } },
  servers:[{ url:"https://auth-demo-rouge.vercel.app", description:"Production" }],
  components:{ securitySchemes:{ ApiKey:{ type:"apiKey", in:"header", name:"X-API-Key" }, CookieAuth:{ type:"apiKey", in:"cookie", name:"access_token" } } },
  security:[{ ApiKey:[] },{ CookieAuth:[] }],
  tags:[{name:"Auth",description:"Registration, login, logout, session"},{name:"Risk Engine",description:"Auth Risk + Engine Risk evaluation"},{name:"SCA / PSD2",description:"Strong Customer Authentication challenges"},{name:"Device Attestation",description:"18-signal device trust evaluation"},{name:"WebAuthn / Passkeys",description:"FIDO2 L2 passkey registration and authentication"},{name:"Sessions",description:"Session management and revocation"},{name:"Admin",description:"Tenant admin — users, transactions, risk rules"},{name:"Tenant",description:"Tenant onboarding and configuration"}],
  paths:{
    "/api/auth/register":{ post:{ tags:["Auth"], summary:"Register a new user", operationId:"registerUser", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", required:["email","password"], properties:{ email:{type:"string",format:"email",example:"alice@example.com"}, password:{type:"string",minLength:8,example:"SecurePass123!"}, displayName:{type:"string",example:"Alice Smith"} }}}}}, responses:{ "200":{ description:"User registered — access_token and refresh_token cookies set"}, "400":{description:"Validation error"}, "409":{description:"Email already exists"}}}},
    "/api/auth/login":{ post:{ tags:["Auth"], summary:"Authenticate user — evaluates risk, may trigger SCA step-up", operationId:"loginUser", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", required:["email","password"], properties:{ email:{type:"string",format:"email"}, password:{type:"string"}, fingerprint:{type:"string",description:"16-hex SHA-256 device fingerprint"} }}}}}, responses:{ "200":{ description:"Login result with optional SCA step-up", content:{"application/json":{ schema:{ type:"object", properties:{ user:{type:"object"}, scaRequired:{type:"boolean"}, method:{type:"string",enum:["totp","webauthn","push","email_otp"]}, sessionId:{type:"string"}, risk:{type:"object",properties:{score:{type:"integer"},level:{type:"string"},decision:{type:"string"}}} }}}}}, "401":{description:"Invalid credentials"}}}},
    "/api/auth/logout":{ post:{ tags:["Auth"], summary:"Revoke current session", operationId:"logout", responses:{"200":{description:"Session revoked"}}}},
    "/api/auth/me":{ get:{ tags:["Auth"], summary:"Get current user + full JWT claims", operationId:"getMe", responses:{ "200":{ description:"Session info", content:{"application/json":{ schema:{ type:"object", properties:{ user:{type:"object"}, claims:{ type:"object", properties:{ sub:{type:"string"}, email:{type:"string"}, tid:{type:"string",description:"Tenant ID"}, sid:{type:"string",description:"Session ID"}, did:{type:"string",description:"Device ID"}, dfp:{type:"string",description:"Device fingerprint (SHA-256)"}, amr:{type:"array",items:{type:"string"},description:"Authentication methods ref"}, acr:{type:"string",enum:["bronze","silver","gold"],description:"Authentication context ref"}, risk:{type:"integer",minimum:0,maximum:100}, risk_lvl:{type:"string",enum:["low","medium","high","critical"]}, sca:{type:"boolean"}, sca_method:{type:"string"}, sca_ts:{type:"integer",description:"Unix timestamp of SCA completion"}, ttype:{type:"string",enum:["access","refresh"]}, roles:{type:"array",items:{type:"string"}}, iat:{type:"integer"}, exp:{type:"integer"}, iss:{type:"string"} }} }}}}}, "401":{description:"Not authenticated"}}}},
    "/api/auth-risk":{ post:{ tags:["Risk Engine"], summary:"Evaluate Auth Risk — Device Trust Layer + Network/Geo Layer", description:"AuthRiskScore = min(100, DeviceTrustScore + NetworkGeoScore). Override rules A–E applied.", operationId:"evaluateAuthRisk", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", properties:{ signals:{ type:"object", properties:{ knownDevice:{type:"boolean",description:"Device fingerprint matches a bound device (−35)"}, deviceHealthy:{type:"boolean",description:"Device attestation passed (−25)"}, biometricUsed:{type:"boolean",description:"Biometric authentication used (−15)"}, screenLockEnabled:{type:"boolean",description:"Screen lock active (−10)"}, developerMode:{type:"boolean",description:"Developer mode enabled (+20)"}, rootedDevice:{type:"boolean",description:"Rooted or jailbroken (+35)"}, vpnDetected:{type:"boolean",description:"VPN active (+10)"}, torExitNode:{type:"boolean",description:"Tor exit node (+30)"}, highRiskCountry:{type:"boolean",description:"High-risk country (+20)"}, ipReputationClean:{type:"boolean",description:"IP reputation clean (−10)"}, asnResidential:{type:"boolean",description:"ASN is residential (−5)"} }}, ip:{type:"string"}, userAgent:{type:"string"} }}}}}, responses:{"200":{ description:"Risk evaluation", content:{"application/json":{ schema:{ type:"object", properties:{ authRiskScore:{type:"integer"}, authRiskLevel:{type:"string"}, authRecommendedAction:{type:"string",enum:["ALLOW","STEP_UP","DENY"]}, layerScores:{type:"object",properties:{deviceTrustScore:{type:"integer"},networkGeoScore:{type:"integer"}}}, scoreBreakdown:{type:"array"}, overrideApplied:{type:"boolean"} }}}}}}}},
    "/api/engine-risk":{ post:{ tags:["Risk Engine"], summary:"Evaluate Engine Risk — 4 layers consolidated 50/50 with Auth Risk", description:"FinalRiskScore = round((AuthRiskScore × 0.5) + (EngineRiskScore × 0.5))", operationId:"evaluateEngineRisk", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", required:["authRiskScore"], properties:{ authRiskScore:{type:"integer",minimum:0,maximum:100}, failedLoginsLast24h:{type:"integer"}, accountAgeDays:{type:"integer"}, passwordBreached:{type:"boolean"}, mfaEnabled:{type:"boolean"}, sessionDurationMinutes:{type:"integer"}, concurrentSessions:{type:"integer"}, geoVelocityKmH:{type:"integer"}, operationType:{type:"string",enum:["login","payment","account_change","data_export"]}, operationAmountEur:{type:"number"}, scaMethod:{type:"string"}, scaChallengesLast7d:{type:"integer"} }}}}}, responses:{"200":{ description:"Engine risk result", content:{"application/json":{ schema:{ type:"object", properties:{ finalRiskScore:{type:"integer"}, engineRiskScore:{type:"integer"}, authRiskScore:{type:"integer"}, decision:{type:"string",enum:["ALLOW","STEP_UP","DENY"]}, layers:{type:"object"}, overrideApplied:{type:"string",nullable:true} }}}}}}}},
    "/api/risk/evaluate":{ post:{ tags:["Risk Engine"], summary:"Standalone risk evaluate for sensitive operations (payment, account change)", description:"Call this during any risky operation outside of login/signup to get a risk decision and optional SCA trigger.", operationId:"evaluateRisk", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", properties:{ context:{type:"string",enum:["login","operation","payment","account_change"],default:"operation"}, operationType:{type:"string"}, amount:{type:"string",example:"250.00"}, currency:{type:"string",default:"EUR"}, signals:{type:"object"}, ip:{type:"string"}, userId:{type:"string"}, sessionId:{type:"string"} }}}}}, responses:{"200":{ description:"Risk evaluation result", content:{"application/json":{ schema:{ type:"object", properties:{ evaluationId:{type:"string"}, score:{type:"integer"}, level:{type:"string"}, decision:{type:"string"}, requiredAction:{type:"string",nullable:true}, scaMethod:{type:"string",nullable:true}, triggeredSignals:{type:"array"}, jwtClaims:{type:"object"}, evaluatedAt:{type:"string"} }}}}}}}},
    "/api/sca/challenge":{ post:{ tags:["SCA / PSD2"], summary:"Create single-use SCA challenge with dynamic linking", description:"Creates a challenge binding amount+IBAN. TTL: 600 seconds. Consumed on verify.", operationId:"createScaChallenge", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", required:["method"], properties:{ method:{type:"string",enum:["totp","webauthn","push","email_otp"]}, amount:{type:"string",example:"250.00"}, iban:{type:"string",example:"LV80BANK0000435195001"}, currency:{type:"string",default:"EUR"}, operationType:{type:"string",default:"payment"} }}}}}, responses:{"200":{ description:"Challenge created", content:{"application/json":{ schema:{ type:"object", properties:{ challengeId:{type:"string",example:"chl_abc123xyz"}, ttl:{type:"integer",example:600}, method:{type:"string"}, createdAt:{type:"string"} }}}}}}}}  ,
    "/api/sca/verify":{ post:{ tags:["SCA / PSD2"], summary:"Verify SCA challenge — returns ALLOW or DENY only (single-use)", operationId:"verifyScaChallenge", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", required:["challengeId","method"], properties:{ challengeId:{type:"string"}, method:{type:"string",enum:["totp","webauthn","push","email_otp"]}, otp:{type:"string",description:"6-digit code for totp or email_otp"}, amount:{type:"string"}, iban:{type:"string"} }}}}}, responses:{"200":{ description:"Verification result", content:{"application/json":{ schema:{ type:"object", properties:{ result:{type:"string",enum:["ALLOW","DENY"]}, reason:{type:"string",nullable:true}, scaMethod:{type:"string"}, challengeId:{type:"string"}, jwtClaims:{type:"object",properties:{sca:{type:"boolean"},sca_method:{type:"string"},acr:{type:"string"},amr:{type:"array"},sca_ts:{type:"integer"}}} }}}}}}}},
    "/api/device-attestation":{ post:{ tags:["Device Attestation"], summary:"Evaluate device attestation (18 signals → healthy/degraded/restricted/blocked/unknown)", operationId:"attestDevice", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", properties:{ signals:{type:"object",description:"Map of signal code to boolean. Codes: KD,DH,BIO,SLE,TPM,SEA,DEV,ROOT,EMU,DBG,HOOK,INT,VPN,TOR,GEO,IPR,ASN,OS"}, platform:{type:"string",enum:["ios","android","web","windows"]}, deviceId:{type:"string"} }}}}}, responses:{"200":{ description:"Attestation result", content:{"application/json":{ schema:{ type:"object", properties:{ status:{type:"string",enum:["healthy","degraded","restricted","blocked","unknown"]}, trustScore:{type:"integer"}, dba:{type:"string",description:"Device Binding Action: allowed/restricted/deny"}, signals:{type:"object",properties:{triggered:{type:"array"},passed:{type:"array"}}}, recommendation:{type:"string"} }}}}}}}},
    "/api/webauthn/register/begin":{ post:{ tags:["WebAuthn / Passkeys"], summary:"Begin WebAuthn registration", operationId:"webauthnRegisterBegin", requestBody:{required:true,content:{"application/json":{schema:{type:"object",required:["email"],properties:{email:{type:"string"}}}}}}, responses:{"200":{description:"PublicKeyCredentialCreationOptions"}}}},
    "/api/webauthn/register/finish":{ post:{ tags:["WebAuthn / Passkeys"], summary:"Complete WebAuthn registration", operationId:"webauthnRegisterFinish", requestBody:{required:true,content:{"application/json":{schema:{type:"object",properties:{email:{type:"string"},response:{type:"object"}}}}}}, responses:{"200":{description:"Credential stored",content:{"application/json":{schema:{type:"object",properties:{verified:{type:"boolean"},credentialId:{type:"string"}}}}}}}}},
    "/api/webauthn/auth/begin":{ post:{ tags:["WebAuthn / Passkeys"], summary:"Begin WebAuthn authentication", operationId:"webauthnAuthBegin", requestBody:{required:true,content:{"application/json":{schema:{type:"object",properties:{email:{type:"string"}}}}}}, responses:{"200":{description:"PublicKeyCredentialRequestOptions"}}}},
    "/api/webauthn/auth/finish":{ post:{ tags:["WebAuthn / Passkeys"], summary:"Complete WebAuthn authentication — issues JWT session", operationId:"webauthnAuthFinish", requestBody:{required:true,content:{"application/json":{schema:{type:"object",properties:{email:{type:"string"},response:{type:"object"}}}}}}, responses:{"200":{description:"Authenticated",content:{"application/json":{schema:{type:"object",properties:{verified:{type:"boolean"},token:{type:"string"}}}}}}}}},
    "/api/sessions":{ get:{ tags:["Sessions"], summary:"List active sessions", operationId:"listSessions", responses:{"200":{description:"Sessions"}}}, delete:{ tags:["Sessions"], summary:"Revoke session by ID", operationId:"revokeSession", requestBody:{required:true,content:{"application/json":{schema:{type:"object",required:["sessionId"],properties:{sessionId:{type:"string"}}}}}}, responses:{"200":{description:"Revoked"}}}},
    "/api/transactions":{ get:{ tags:["Admin"], summary:"List auth transactions (paginated)", operationId:"listTransactions", security:[{ApiKey:[]},{CookieAuth:[]}], parameters:[{in:"query",name:"type",schema:{type:"string",enum:["auth","token_rotation","session_expiry","risk","sca","attestation","device_binding"]}},{in:"query",name:"userId",schema:{type:"string"}},{in:"query",name:"limit",schema:{type:"integer",default:50}},{in:"query",name:"offset",schema:{type:"integer",default:0}}], responses:{"200":{description:"Transactions"}}}, post:{ tags:["Admin"], summary:"Record a transaction event", operationId:"createTransaction", security:[{ApiKey:[]},{CookieAuth:[]}], requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", properties:{ type:{type:"string",description:"Transaction type e.g. auth, payment, risk"}, userId:{type:"string"}, deviceId:{type:"string"}, ip:{type:"string"}, metadata:{type:"object"} }}}}}, responses:{"200":{ description:"Transaction recorded", content:{"application/json":{ schema:{ type:"object", properties:{ id:{type:"string"}, tid:{type:"string"}, ts:{type:"integer"}, status:{type:"string",example:"recorded"} }}}}}}}},
    "/api/admin/users":{ get:{ tags:["Admin"], summary:"List all tenant users with risk + session summary", operationId:"listUsers", parameters:[{in:"query",name:"search",schema:{type:"string"}}], responses:{"200":{description:"Users"}}}},
    "/api/admin/risk-rules":{ get:{ tags:["Admin"], summary:"Get tenant risk rules", operationId:"getRiskRules", responses:{"200":{description:"Rules"}}}, put:{ tags:["Admin"], summary:"Update tenant risk rules", operationId:"updateRiskRules", requestBody:{required:true,content:{"application/json":{schema:{type:"object"}}}}, responses:{"200":{description:"Saved"}}}},
    "/api/admin/settings":{ get:{ tags:["Tenant"], summary:"Get tenant configuration (JWT, device binding, attestation/risk signals)", operationId:"getSettings", responses:{"200":{description:"Settings"}}}, put:{ tags:["Tenant"], summary:"Update tenant configuration", operationId:"updateSettings", requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", properties:{ jwt:{ type:"object", properties:{ accessTokenTtlSeconds:{type:"integer",default:900,description:"Access token TTL in seconds (default 15 min)"}, refreshTokenTtlSeconds:{type:"integer",default:2592000,description:"Refresh token TTL (default 30 days)"}, sessionRotationSeconds:{type:"integer",default:86400,description:"Session rotation interval (default 24h)"}, excludedClaims:{type:"array",items:{type:"string"},description:"Claims to exclude from JWT"} }}, deviceBinding:{ type:"object", properties:{ maxDevicesPerUser:{type:"integer",default:3}, requireAttestationForBinding:{type:"boolean"}, silentLoginIfRiskLow:{type:"boolean"}, riskThresholdForSilentLogin:{type:"integer",default:25} }}, attestation:{ type:"object", properties:{ disabledSignals:{type:"array",items:{type:"string"},description:"Signal codes to ignore during evaluation"}, minimumStatus:{type:"string",enum:["healthy","degraded","restricted"]} }}, risk:{ type:"object", properties:{ disabledSignals:{type:"array",items:{type:"string"},description:"Risk signal keys to ignore"} }} }}}}}, responses:{"200":{description:"Saved"}}}},
    "/api/admin/api-key":{ get:{ tags:["Admin"], summary:"Get tenant API key (masked)", operationId:"getApiKey", security:[{CookieAuth:[]}], responses:{"200":{ description:"API key info", content:{"application/json":{ schema:{ type:"object", properties:{ keyPrefix:{type:"string",example:"uth_live_"}, keySuffix:{type:"string",description:"Last 4 chars"}, keyMasked:{type:"string"}, createdAt:{type:"string"}, tid:{type:"string"} }}}}}}}, post:{ tags:["Admin"], summary:"Regenerate tenant API key", operationId:"regenerateApiKey", security:[{CookieAuth:[]}], requestBody:{ required:true, content:{"application/json":{ schema:{ type:"object", required:["action"], properties:{ action:{type:"string",enum:["regenerate"]} }}}}}, responses:{"200":{ description:"New API key", content:{"application/json":{ schema:{ type:"object", properties:{ key:{type:"string",description:"Full new API key — store securely"}, createdAt:{type:"string"}, tid:{type:"string"} }}}}}}}},
    "/api/tenants":{ post:{ tags:["Tenant"], summary:"Create new tenant (onboarding)", operationId:"createTenant", requestBody:{required:true,content:{"application/json":{schema:{type:"object",required:["name","plan"],properties:{name:{type:"string"},domain:{type:"string"},plan:{type:"string",enum:["starter","growth","enterprise"]}}}}}}, responses:{"200":{description:"Tenant created with API key"}}}},
  }
};
