import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
function Nav() {
  return (<nav className="border-b border-white/8 px-6 py-4 flex items-center justify-between sticky top-0 bg-zinc-950/90 backdrop-blur-xl z-50"><Link href="/" className="flex items-center gap-2.5"><div className="w-7 h-7 rounded-md bg-indigo-600 flex items-center justify-center"><span className="font-black text-white text-xs">UTH</span></div><span className="font-black tracking-tighter text-lg"><span className="text-indigo-400">U</span><span className="text-indigo-300">T</span><span className="text-indigo-200">H</span></span></Link><div className="flex gap-4 text-sm text-zinc-400"><Link href="/privacy" className="hover:text-white">Privacy</Link><Link href="/terms" className="hover:text-white">Terms</Link></div></nav>);
}
function S({ title, children }: { title: string; children: React.ReactNode }) {
  return (<section className="mb-10"><h2 className="text-xl font-bold text-white mb-4 pb-2 border-b border-zinc-800">{title}</h2><div className="space-y-3 text-zinc-400 text-sm leading-relaxed">{children}</div></section>);
}
const COMMITMENTS = ["Processing personal data only on documented instructions, as per our contract with you or as required by law","Implementing suitable technical and organisational safeguards, such as endpoint protection, encryption, secure remote access, and access control policies","Ensuring that only authorised personnel under confidentiality obligations can access personal data","Engaging sub-processors only with your consent and ensuring they follow the same data protection standards","Alerting you if we believe your instructions may lead to a GDPR violation","Assisting you in responding to data subject requests and inquiries from regulatory authorities","Promptly notifying you of any data breaches or suspected breaches that could compromise your information","Ensuring appropriate legal safeguards for any transfers of personal data outside the EU/EEA"];
export default function GDPRPage() {
  return (<div className="min-h-screen bg-zinc-950 text-white"><Nav /><div className="max-w-3xl mx-auto px-6 py-16"><div className="mb-12"><div className="text-xs text-zinc-500 uppercase tracking-widest mb-2">Legal · UTH</div><h1 className="text-4xl font-black text-white mb-3">GDPR</h1><p className="text-zinc-400 text-lg font-medium">UTH Takes Data Privacy Seriously</p></div>
  <S title="What is the GDPR?"><p>The General Data Protection Regulation (GDPR) has been in effect since 25 May 2018. It applies uniformly across all EU and EEA countries. The goals of the GDPR are to: harmonize data protection laws across the EU; modernise regulations in light of technological advancements; strengthen individual rights over personal data; increase accountability for data controllers and processors; and promote transparency in how, by whom, and for what purposes data is processed.</p><p>The GDPR applies to any organisation processing the personal data of individuals within the EU, regardless of the company&apos;s location.</p></S>
  <S title="Our GDPR commitment"><p>UTH acts as both a data controller and processor and is committed to GDPR compliance. We have undertaken a thorough programme including: conducting a global audit of our data processing activities; reviewing and strengthening data security across all business units; updating internal policies, staff training, and data governance procedures; establishing GDPR-compliant agreements with all data processors and sub-processors; reviewing our use of cookies and tracking technologies; and improving user consent and marketing preference management.</p></S>
  <S title="GDPR and UTH"><p>The UTH authentication platform is designed with GDPR compliance as a first-class concern. UTH provides a data erasure API (right to erasure), JSON data export (portability), cryptographic pseudonymisation of device fingerprints, configurable audit log retention with automatic expiry, and a Data Processing Agreement for all customers.</p></S>
  <div className="rounded-xl border border-zinc-800 bg-zinc-900 p-6 mb-10"><h3 className="font-semibold text-white mb-4">Our commitments</h3><div className="space-y-3">{COMMITMENTS.map((c, i) => (<div key={i} className="flex items-start gap-2.5 text-sm text-zinc-400"><CheckCircle2 className="w-4 h-4 text-green-400 mt-0.5 shrink-0" /><span>{c}</span></div>))}</div></div>
  </div><footer className="border-t border-white/8 px-6 py-6 text-center text-zinc-700 text-xs"><Link href="/" className="hover:text-zinc-400">← Back to UTH</Link></footer></div>);
}
